### ISSUE TITLE
Data Export Error!

### ISSUE THREAD

**Issue by github-oken** [XLSForm/xlsform.github.io#113]
I have a challenge exporting data from ona.io. This is the first time I am having this issues. The form contains one repeated group. The data export link is generated successfully but when I click the link to download I get the screenshot below. Please how do I solve this problem.

![image](https://user-images.githubusercontent.com/10453181/37733609-f3ec2cc0-2d48-11e8-87cb-69748ddc2320.png)

**Comment by MartijnR** [comment]
Best to contact Ona about this: https://ona.io/contact.html

This repository is for XLSForm documentation.
