### ISSUE TITLE
Enable contributors to translate the content

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/xlsform.github.io#123]
I've had a request from a user who wants to help translate XLSForm.org into French. I bet we can probably find people to translate it into a bunch of languages if the infrastructure is in place. Is this something you'd be interested in taking on @MartijnR? 

Some resources
* http://polyglot.untra.io
* https://www.klaasnotfound.com/2017/02/16/proper-multilingual-site-with-github-pages-and-jekyll

**Comment by MartijnR** [comment]
That's great!

Yes, I think that would be within the scope of the DIAL funding and I should have time and interest for this. Let me make some calculations!

**Comment by MartijnR** [comment]
* [ ] select plugin
* [ ] build nav menu automatically (using same script as in ODK XForms Spec)
* [ ] either [publish build to gh-pages branch](https://github.com/untra/polyglot/wiki/Github-Pages-Support) and use master for development or host elsewhere

**Comment by MartijnR** [comment]
For the ref-table, I think we need a different solution. It's already a pain to edit, and maintaining two different language versions of it would be less fun (keeping all the yes/no/alias in sync). One CSV file including language columns would be better. We could use build script to convert to HTML (not markdown to avoid accidental markdown editing)  in this branch or publish a build to the `gh-pages` branch.

**Comment by MartijnR** [comment]
* [ ] fix heading links in ref-table
* [ ] don't show language selector whilst we have only one language
