### ISSUE TITLE
Accessing Choice metadata in a Forumla

### ISSUE THREAD

**Issue by MattFoy** [XLSForm/xlsform.github.io#131]
Apologies if this is already a thing and I'm just being ignorant.

I noticed in the documentation under http://xlsform.org/#cascade, you can make selects filter based on "metadata" from the `choices` list. In the example given, you add a `choice_filter` column, and can set it like `state=${state} and county=${county}`. The "state" and "country" apparently referencing those extra metadata columns from the list of choices.

Rather than _filtering_, I'd like to display the full list, then merely _display_ or perhaps reference that metadata once a selection has been made. This would be useful for a number of use cases I can think of.

I would expect to be able to access this metadata in a `calculation` column like `${city->county}` or `${city.county}` or something like that... or maybe in a `relevant` column like `${city}->altitude >= 1000` or `${city}.altitude >= 1000`.

If this is a thing already, could you please point me towards the proper syntax?

Thanks!

**Comment by lognaturel** [comment]
You can do this! It has no special support in XLSForm but you can use [XPath queries](https://docs.oracle.com/cd/E18442_01/doc.651/e18053/xpath.htm) and those are just passed through to the form XML. See https://docs.google.com/spreadsheets/d/1mQGVWaJA4QQp3jtddMdcRSDjc1O-j_bB79GUnlj5k10/edit#gid=0 for an example.

https://github.com/XLSForm/pyxform/issues/176 would be a first step towards more native support for this.

In general, something like the ODK forum (https://forum.opendatakit.org/) will be a better place for a usage question. If there is development to be done someone can help direct you to the best repository for filing the issue!

**Comment by MattFoy** [comment]
Thanks!!
