### ISSUE TITLE
Document question name restrictions

### ISSUE THREAD

**Issue by jnm** [XLSForm/xlsform.github.io#142]
If Pyxform is the authoritative source: "Names must begin with a letter, colon, or underscore. Subsequent characters can include numbers, dashes, and periods." There's mention of recommendations, but not requirements, in https://github.com/XLSForm/xlsform.github.io/issues/24.

See:
* https://github.com/XLSForm/pyxform/blob/1493706622c329fd2913ae691a902bca054250d4/pyxform/utils.py#L28-L34
* https://github.com/XLSForm/pyxform/blob/1493706622c329fd2913ae691a902bca054250d4/pyxform/xls2json.py#L584-L594

**Comment by MartijnR** [comment]
Yes would be good! I think starting with a colon is actually not allowed. Will create PR based on XML nodename rules.
