### ISSUE TITLE
Home page problem for french

### ISSUE THREAD

**Issue by CorentinLemaitre** [XLSForm/xlsform.github.io#143]
Hello, 

I have a problem on the home page. First information i am french. When i go to xlsform.org a page appear (for 1 second) and redirect me to the xlsform.org/fr/ 
![image](https://user-images.githubusercontent.com/20289907/44844332-e4253080-ac4a-11e8-9caa-110dd8360aa0.png)
Then i get a 404 error because there is no fr directory.
I have acheive to go to access to the website with this link xlsform.org/en/

I have seen that french translation is a current project so may be a problem to fix soon. I will be happy to help for the translation.

**Comment by MartijnR** [comment]
Thanks and sorry about this!

Will quickly check if we can just prevent the redirect from happening for untranslated languages, and otherwise merge your PR.

**Comment by MartijnR** [comment]
Oops, merged like a dictator. But okay in this case I hope.

P.S. you may see the old redirect for a little while if the page is still cached in the browser, but it's confirmed fixed.
