### ISSUE TITLE
Let's add more platforms link onto our webpage which supports XLSForm conversion

### ISSUE THREAD

**Issue by vivonk** [XLSForm/xlsform.github.io#163]
This company also supports XLSForm conversion. Please add them as well
https://socialcops.com/collect/

**Comment by vivonk** [comment]
@MartijnR can we add them as well?

**Comment by yanokwa** [comment]
@vivonk, it's not clear SocialCops supports XLSForm.

@MartijnR I'd like to propose that we review the links and If the website doesn't mention XLSForm, we shouldn't link to it.
