### ISSUE TITLE
cascading select sample form incorrect

### ISSUE THREAD

**Issue by tiritea** [XLSForm/xlsform.github.io#174]
sample form for cascading selects, called  "new_cascading_select"
 (here https://docs.google.com/spreadsheet/ccc?key=0AjZ4hMHTat-YdFVpOWVBVWREUGdNVWZKbUl2akhfWkE&usp=sharing), is wrong:

The choice_filter for city has "cf=${state} and cf=${county}" but should be "cf=${county}". Currently, city cf will never match state, so the 3rd selection choice list will always be blank.

**Comment by MartijnR** [comment]
Indeed. Not sure who the owner is. I wonder if we should serve .xlsx files from a folder on xlsform.org instead.

**Comment by lognaturel** [comment]
> I wonder if we should serve .xlsx files from a folder on xlsform.org instead.

I'm in strong support of that. I like that Google Sheets open in browser but in this case I think it's useful to have history and shared ownership.

**Comment by tiritea** [comment]
agreed. sample forms we explicitly refer to in the docs should probably be tracked/managed/owned in a similar manner.
