### ISSUE TITLE
file upload type missing from reference table?

### ISSUE THREAD

**Issue by danbjoseph** [XLSForm/xlsform.github.io#209]
the `file` type question as described in the ODK docs [here](https://docs.getodk.org/form-question-types/#file-upload-widget) is not included in the XLSForm [reference table](https://xlsform.org/en/ref-table/). it is included on the main docs page under [question types](https://xlsform.org/en/#question-types).
- should it be included in the reference table?
- is it compatible with Enketo?

**Comment by MartijnR** [comment]
yes and yes. Thanks!
