### ISSUE TITLE
Add undocumented calculates that are in ODK

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/xlsform.github.io#21]
"There are almost certainly calculate functions that are not documented in XLSForm."
– Mitch

**Comment by MartijnR** [comment]
Very true... We should put a version of the XForms Xpath functions table in this spec that is more accessible. There is a short list in the ref table but I don't think it belongs there.

**Comment by yanokwa** [comment]
Not sure this is actionable, but we do have a decent list at https://docs.opendatakit.org/form-operators-functions. If xlsform switches to Sphinx as a platform, then you could pull that in easily. 

A likely easier alternative is to link to the spec at https://opendatakit.github.io/xforms-spec.

**Comment by yanokwa** [comment]
Links are free, so you could link to both!  

Say one is the technical spec and the other is more user-friendly and focused on ODK Collect, but it should work everywhere, probably.
