### ISSUE TITLE
Document "name" column in settings sheet.

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/xlsform.github.io#214]
This overrides the default "data" name of the form.

**Comment by lognaturel** [comment]
https://xlsform.org/en/#specify-xforms-root-node-name

**Comment by MartijnR** [comment]
Ah! Thanks. Should it be in https://xlsform.org/en/#settings-worksheet as well?

**Comment by lognaturel** [comment]
Oh, yes, definitely! Ideally the elements of the list would link down to the detail sections.

**Comment by MartijnR** [comment]
yes, that would be good
