### ISSUE TITLE
broken link talking about search() expression

### ISSUE THREAD

**Issue by danbjoseph** [XLSForm/xlsform.github.io#230]
the "this post" linked here doesn't exist anymore and redirects to the Get ODK home page
https://github.com/XLSForm/xlsform.github.io/blob/48637dd3fec873ce55d0598fed578ad86c6a2491/_sections/home-english.md?plain=1#L898

**Comment by msschroeder** [comment]
This should be resolved with the additional of search parameters in pull request #166
