### ISSUE TITLE
Add links to all known XLSForm converters

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/xlsform.github.io#25]
There are a number of XLSForm converters (especially the offline tools) that should be added to this site.
- Nafundi's [XLSForm Offline](https://gum.co/xlsform-offline) is a beautiful offline app for Windows and Mac. It's always available, seriously fast, completely secure, and refreshingly easy to use.
- Nathan Breit's [xlsform.exe](https://github.com/UW-ICTD/xlsform.exe/blob/master/README.md) works offline and runs on some Windows systems.
- http://formhub.org
- http://ona.io
- http://surveycto.com

**Comment by vivonk** [comment]
@yanokwa I found a good platform and they also have XLS Form converter. Please add them as well
https://socialcops.com/collect/
@smusula

**Comment by yanokwa** [comment]
@vivonk Are you the same Nirmal Sarswat at https://socialcops.com/about/team? If so, it'd be good to disclose your affiliation.
