### ISSUE TITLE
Update the broken Google drive link

### ISSUE THREAD

**Issue by samwata** [XLSForm/xlsform.github.io#267]
The google drive form that was meant to be attached [here](https://xlsform.org/en/#dynamic-selects-from-pre-loaded-data) under [XLSform.org](http://xlsform.org/) documentation seems to be broken
Under this statement "For an example, see the [advanced search-and-select](https://drive.google.com/drive/folders/1Wx09ZFOJuiWmy0XKKtpxzGsZHfxeTO9c?usp=sharing)

it throws 404 error
![image](https://github.com/XLSForm/xlsform.github.io/assets/23456184/78074a2d-1568-4ccf-980c-e192c2d51a31)

**Comment by samwata** [comment]
Closing this 
it is related to https://github.com/XLSForm/xlsform.github.io/issues/261

**Comment by jenn-karuri** [comment]
Issue resolved. The link was added [here](https://xlsform.org/en/#dynamic-selects-from-pre-loaded-data) on the site under Dynamic selects from pre-loaded data
