### ISSUE TITLE
Enhancement: Sticky Nav Menu

### ISSUE THREAD

**Issue by joehand** [XLSForm/xlsform.github.io#34]
It'd be great to have a sticky navigation menu e.g. http://codepen.io/yowainwright/pen/bmLgA

**Comment by wilo99** [comment]
Javascript based solution: Sticky ahttps://jsfiddle.net/mekwall/up4nu/

**Comment by MartijnR** [comment]
This can be closed, as it was done, it seems (and @joehand has sadly left the ODK world for greener pastures).

**Comment by joehand** [comment]
❤️
