### ISSUE TITLE
Media example form is missing audio file

### ISSUE THREAD

**Issue by tinok** [XLSForm/xlsform.github.io#44]
question.wav doesn't seem to have been included in the birds media form (https://docs.google.com/spreadsheets/d/1Rxft3H3xl3M9bLFGR2XhXzt1ucyFmd0qFmOQ6FaqJw4/edit#gid=246559171). 

Check https://l2sje.enketo.org/webform and try to play the audio on question 'What bird did you see?'

**Comment by MartijnR** [comment]
The file can be downloaded here: http://formhub.org/formhub_u/forms/Birds/formid-media/119639

Not sure where it should be placed though.

**Comment by MartijnR** [comment]
I guess this was resolved. https://enke.to/::birds
