### ISSUE TITLE
Are there any valid Appearance values for Geopoint questions?

### ISSUE THREAD

**Issue by Cintruenigo** [XLSForm/xlsform.github.io#46]
Are there any valid Appearance values for Geopoint questions?

**Comment by MartijnR** [comment]
I think just these:

`maps` to show a map (on any device)
`hide-input` to hide input fields by default so a larger map is shown (Enketo only)

in action here: https://geo.enketo.org/webform

**Comment by Cintruenigo** [comment]
Thanks Martin!
