### ISSUE TITLE
Add appearance=compact, and appearance=quickcompact to table

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/xlsform.github.io#53]
Seem to be missing

Is appearance=quick correct?

**Comment by tinok** [comment]
Do you have a suggestion for the description field?

**Comment by MartijnR** [comment]
Appearance=compact => 'Creates a grid of options, only showing the label text or media'. (I think this is the same as appearance=horizontal, except that it only shows the label/media, not the tickboxes and radiobuttons).

Appearance=quickcompact => same, but advances to next question upon selection (in ODK Collect only).

**Comment by MartijnR** [comment]
I may have misunderstood this and may need a different description.

**Comment by JohnHasthorpe** [comment]
Linking to: https://devtopia.esri.com/Melbourne/Survey123/issues/1623

**Comment by MartijnR** [comment]
I think we can:

* replace `horizontal-compact` with `compact` (and make `horizontal-compact` an alias)
* consider `quickcompact` the same as `quick compact` and `compact quick`. (This means we could actually also take it out entirely)

**Comment by capitalgerald** [comment]
I welcome @MartijnR view
