### ISSUE TITLE
Login issue to app and survey not displaying

### ISSUE THREAD

**Issue by KirstyNZ** [XLSForm/xlsform.github.io#58]
Hi, 

I am unable to login to the app via my ArcGIS Online account, even though I am able to login via the web on the computer and through the Collector app on the same device. The error message is "Unable to generate token. Invalid username and password."

In a seperate issue, the desktop applicaton for the software will not display correctly. When opening up a survey, the error message displayed is shown in the image below.

This is my first trial of the software so it may be something to do with my downloading and setup.

Cheers
![screen shot 2015-09-18 at 10 11 48 am](https://cloud.githubusercontent.com/assets/14324326/9949619/48f7edfc-5e03-11e5-89c6-42121d3a9bcd.png)

**Comment by MartijnR** [comment]
Wrong place. Survey123 just links to this form format documentation repository. Best to contact the Survey123/esri folks.
