### ISSUE TITLE
Add type=file

### ISSUE THREAD

**Issue by cagulas** [XLSForm/xlsform.github.io#64]

**Comment by cagulas** [comment]
Blocked by: https://github.com/onaio/enketo-express/issues/22

**Comment by cagulas** [comment]
Unblocked.

All file types are supported.  Not clear if there's any file size limit though.

**Comment by MartijnR** [comment]
file size limit is the same for all files. It is set in the Ona, KoBo, ODK Aggregate server. The clients (Enketo, ODK Collect) should respect this value. In Ona it's currently set to 100 Mb I believe (huge).

**Comment by tiritea** [comment]
Curious, how does (will?) a new control type='file' differ from what is already available in the XForms spec via <upload mediatype='foo'>? [see https://en.wikibooks.org/wiki/XForms/Upload]

**Comment by MartijnR** [comment]
Within our ecosystem, the use is more restricted (simpler syntax only). We don't support `<filename>` and `<mediatype>` elements.

This is in our spec: https://github.com/opendatakit/xforms-spec/pull/82

So we do something a little weird for uploads in that we support both `mediatype` and `accept` attributes, but for historical reasons deviate from the XForms 1.0 spec with the mediatype attribute. (... and the current pyxform implementation deviates from our own spec until [this](https://github.com/XLSForm/pyxform/issues/101) is fixed).

FYI, this was [the spec discussion](https://github.com/opendatakit/xforms-spec/pull/82).

**Comment by MartijnR** [comment]
I believe the mediatypes belonging to type=file  have not been discussed/documented in the XForm spec yet. I'll write something up and once it's included in the XForm spec, we can add it to the XLSForm spec.
