### ISSUE TITLE
Add a note about HXL support in XLSForms

### ISSUE THREAD

**Issue by pld** [XLSForm/xlsform.github.io#72]
Description of use-case in XLSForms is included here, https://blog.ona.io/features/2016/06/22/full-HXL-support.html

**Comment by MartijnR** [comment]
This feature has no related XForm output, right?

**Comment by MartijnR** [comment]
I realize now these are added as attributes to the primary instance nodes as below:

```xml
<instance>
   <data id="myform">
      <num_of_ppl hxl="#population"/>
      <gps hxl="#gps"/>
      <photo hxl="#photo"/>
      <meta>
        <instanceID/>
      </meta>
    </data>
</instance>
```

So this is using the generic `instance::` feature of XLSForm.

I would be in favor of either:

1. documenting this use of `instance::` where hxl is just an example of its use. So far `instance::` hasn't been documented (deliberately as it was meant for custom features, but we could add an advanced section to document the `instance::`, `body::`, `bind::` feature).

2. Continuing the discussing of a real "code" or "tag" feature as started here: https://forum.opendatakit.org/t/adding-a-code-column-to-xlsforms/4043/13. It got abandoned after identifying a need to code individual "option values", but it is not clear to me how this is currently done in Ona's supported feature (in the XForm).
