### ISSUE TITLE
Recommend "language name (xx)" syntax

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/xlsform.github.io#73]
As agreed in ODK dev forum: https://groups.google.com/forum/#!searchin/opendatakit-developers/language$20names$20proposal%7Csort:relevance/opendatakit-developers/ZLDJanOCudE/T7yTrDMYVAsJ

The rationale is a future feature where UI and form language can be synced (e.g. in a manner as discussed here: https://github.com/kobotoolbox/enketo-express/issues/526).

Language codes available here (called subtags): http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

<img width="180" alt="language-tags" src="https://cloud.githubusercontent.com/assets/627350/16808519/0e0fda34-48da-11e6-8f4c-45c035580260.png">

At the moment, I believe that ODK collect will just copy the whole string including code in the language selector pulldown (so show "English (en)"). Enketo will strip the language code (so show "English").

**Comment by MartijnR** [comment]
and update/add multi-language sample forms

**Comment by lognaturel** [comment]
Seems like there's already agreement on this and it just needs to be "Made So", right?

Might it be worthwhile for pyxform to issue a warning to help users move in that direction?
