### ISSUE TITLE
Relevant for select_multiple options 

### ISSUE THREAD

**Issue by osanwo** [XLSForm/xlsform.github.io#74]
Hello,

I am trying to use  a relevant column to skip a question if all options in the preceding question are not ticked. The preceding question is a multiple select type. I have tried using the sample displayed on the xlsform page but it keeps giving errors when I try to convert the excel to an Xform. Has this attribute been removed? Thanks.

**Comment by MartijnR** [comment]
Assuming this is resolved since July 29th. Sorry you didn't receive a response...
