### ISSUE TITLE
appearance="autocomplete", appearance="autocomplete_chars", appearance="search"

### ISSUE THREAD

**Issue by MartijnR** [XLSForm/xlsform.github.io#79]
There is some confusion about autocomplete functionality on a select_one type questions.

[This table](http://xlsform.org/ref-table/) mentions "autocomplete" and "autocomplete_chars" appearances. Does anybody know where these come from? Does this come from an ODK Collect fork perhaps?

In ODK Collect only appearance="search" appears to be working (on select_one) and it's the only one they describe [here](https://opendatakit.org/help/form-design/examples/).

I'm wondering if we should consider appearance="autocomplete" as an alias of appearance="search" or whether they are something different.

**Comment by MartijnR** [comment]
Looks like autocomplete was removed from ODK Collect in 2011: aca494cfec24c8d746f7117a630ddd7af754a850

**Comment by MartijnR** [comment]
Proposal: 

1. Let appearance="search" (not the "function" version) be an alias of appearance="autocomplete" because we now have two clients that have implemented the same feature under a different name.

2. Let appearance="autocomplete_chars" be removed from docs, unless anybody what this is about and is supported somewhere.

Any objections?

**Comment by yanokwa** [comment]
1. Agreed. Do you also think we should map the autocomplete alias to search in ODK Collect?
1. Agreed.

**Comment by MartijnR** [comment]
Thanks. Yes, I think it would be good to do that mapping in ODK Collect too.

**Comment by MartijnR** [comment]
* [ ] in table put the old "search" in the alias column (instead of a separate row).

I will do this.
