### ISSUE TITLE
Follow up question based on answers.

### ISSUE THREAD

**Issue by RaunoEST** [XLSForm/xlsform.github.io#85]
Hi!

I'm new to XLSform and ran up to a problem, that I'm sure there is simple solution and i can't believe later that i couldn't figure it out by myself.  

I have a question with multiple choices, where each choice is an name of species. The next question needs to be abundance of recorded (selected species).   

For example i recorded two species from list of 20, Alces alces (moose) and Vulpes vulpes (fox). Next question needs to be a field that asks the number of specimens recorded.

Thanks for your time and help.

Rauno

**Comment by lognaturel** [comment]
@RaunoEST this issue tracker is mostly used for spec issues rather than user support. I believe [this answer](https://groups.google.com/d/msg/opendatakit/Q77Rz3MrKkU/TK7B3LTkTAEJ) on the ODK Community list should help you out. That's also the place to ask if you have any other questions!
