### ISSUE TITLE
Remove default hint from geopoint controls

### ISSUE THREAD

**Issue by tiritea** [XLSForm/xlsform.github.io#86]
Using XLSForm Offline 1.4.0 by Nufundi:

XLSForm appears to automatically add the hint "GPS coordinates can only be collected when outside." to any geopoint controls if no hint is explicitly specified by the user. As XLSForm is really just a format translation tool - specifically Excel to XML - it probably should not be adding _semantic_ content to the translated document (IMHO). That, and the statement is technically incorrect to begin with - it's perfectly possible to acquire a GPS fix inside! :-) 

I think this auto-hint should just be removed.

**Comment by MartijnR** [comment]
Totally agree! This repo is just for the documentation. Nafundi has actually already removed this from the tool (pyxform): https://github.com/XLSForm/pyxform/pull/67. I think the Offline app just needs to be updated.

**Comment by tiritea** [comment]
Thanks. I'm new to XLSForm - I'll post any code-related questions (and requests) directly to pyxform in the future.
