### ISSUE TITLE
Remove search appearance-function

### ISSUE THREAD

**Issue by lognaturel** [XLSForm/xlsform.github.io#95]
http://xlsform.org/#dynamic-selects-from-pre-loaded-data

I don't believe any client supports this currently and it's not part of the ODK XForms spec. @MartijnR  has stated previously that Enketo doesn't support it and Collect hasn't supported it for a couple of years.

**Comment by lognaturel** [comment]
This is probably something I should keep on my long-term "to discuss" list more than an immediate issue that can be closed.

Collect does still support it, it's just conflated with the `search` appearance which is an alias for `autocomplete`.

**Comment by MartijnR** [comment]
Ah that's sad news. :sob:

**Comment by lognaturel** [comment]
I know, sorry! But I'm keeping the dream alive. I certainly try to steer people clear.
